/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiJobsJobIdRouteImport } from './routes/api/jobs.$jobId'
import { Route as ApiJobsJobIdResultRouteImport } from './routes/api/jobs.$jobId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdRoute = ApiJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsJobIdResultRoute = ApiJobsJobIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ApiJobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/live': typeof ApiLiveRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/$jobId/result': typeof ApiJobsJobIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/live': typeof ApiLiveRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/$jobId/result': typeof ApiJobsJobIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/live': typeof ApiLiveRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/$jobId/result': typeof ApiJobsJobIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/jobs'
    | '/api/live'
    | '/api/jobs/$jobId'
    | '/api/jobs/$jobId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/jobs'
    | '/api/live'
    | '/api/jobs/$jobId'
    | '/api/jobs/$jobId/result'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/jobs'
    | '/api/live'
    | '/api/jobs/$jobId'
    | '/api/jobs/$jobId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  ApiLiveRoute: typeof ApiLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId': {
      id: '/api/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/jobs/$jobId'
      preLoaderRoute: typeof ApiJobsJobIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$jobId/result': {
      id: '/api/jobs/$jobId/result'
      path: '/result'
      fullPath: '/api/jobs/$jobId/result'
      preLoaderRoute: typeof ApiJobsJobIdResultRouteImport
      parentRoute: typeof ApiJobsJobIdRoute
    }
  }
}

interface ApiJobsJobIdRouteChildren {
  ApiJobsJobIdResultRoute: typeof ApiJobsJobIdResultRoute
}

const ApiJobsJobIdRouteChildren: ApiJobsJobIdRouteChildren = {
  ApiJobsJobIdResultRoute: ApiJobsJobIdResultRoute,
}

const ApiJobsJobIdRouteWithChildren = ApiJobsJobIdRoute._addFileChildren(
  ApiJobsJobIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsJobIdRoute: typeof ApiJobsJobIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsJobIdRoute: ApiJobsJobIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  ApiLiveRoute: ApiLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
